apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: viveksyngh-slack-secrets
  namespace: openfaas-fn
spec:
  encryptedData:
    slack-token: AgAALYjzg18W7Jn1QurY/VfczIRV2f9G6clwTOIfYDQtcvO0xDY5u9mKGCg+9HNprjYRkn36eWEq7oAtrQqCvudJkBN69HPeomZ1pU5d7NhvT+gRD3v9g0gxJNL4SNP0LZFTva+RVtz5786aS19z/4Nd4zQn7EN0bltRGgydv43ISCdp0is0gRyq1CvDD7WPsJS1zwfdl2qo5/Er8SQjdA1SjUp3a4WEWey3eT/JkhJMpfHX1Cs91EjDbcXgeHLjiqYXzbx708fflsRup+bplTQBXvTF+eooSEnzyDzSq21wny8o/9R6skh+eddK7o3wyxwtggBMcWSRsHOjQsoH9jwBV/7cLNJGmmw9l+cv4d9giQsrs724xWeE5V/nzBZ/Nkgd1peOc2YfyntQFHax96UtuBHOJQA+FzPkEyoC9fDO5f0IGKP1zmrv0Jxy/3FKzJFsxDXdM90H84u0rjlla4sUiZ+0LPu4KDx18mBUqf39t0mQaU9pEO/mRHddQV215jXivswWiKf8Ue2B+MoALhmsCmOn/Edkj77j15YI0BJOdNqTjXUzKhJmNv5L27rUu3euBMMJQvx4yLOlYqlD5O5ahgMVOHTiL8aWg2RZEmuULuqk4ME23WeOZaZLc9W5Lc2ifNjIECbL2LWNMp3HUFzp6YG6cHurptONwkwL2d/oYr7kwEkyksmRBgZheKw64vKoctFjBqxwC/GslnP+puWIKONwF0RJvCiQYMDcBtA4lYv5Pe40bcKLqsQXVGU9+kYB+OKRqQGcDqtUIGbE02iaZO9sVIIZa8pEZNzL

