provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  dnd-info:
    lang: go
    handler: ./dnd-info
    image: viveksyngh/dnd-info
    environment:
      combine_output: false
    environment_file:
    - env.yml
    secrets:
      - slack-secrets

  end-dnd:
    lang: go
    handler: ./end-dnd
    image: viveksyngh/end-dnd
    environment:
      combine_output: false
    environment_file:
    - env.yml
    secrets:
      - slack-secrets

  set-snooze:
    lang: go
    handler: ./set-snooze
    image: viveksyngh/set-snooze
    environment:
      combine_output: false
    environment_file:
    - env.yml
    secrets:
      - slack-secrets

  end-snooze:
    lang: go
    handler: ./end-snooze
    image: viveksyngh/end-snooze
    environment:
      combine_output: false
    environment_file:
    - env.yml
    secrets:
      - slack-secrets

  api-webhook:
    lang: go
    handler: ./api-webhook
    image: viveksyngh/api-webhook
    environment:
      combine_output: false
      gateway_url: "http://gateway.openfaas:8080"